version: '3'

services:
  react:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "3003:3000"
    networks:
      - shared_network

networks:
  shared_network:
    external:
      name: my_shared_network



